dist: xenial
services:
- postgresql
before_script:
- psql -c "create user eatsyuser password 'complexpassword';" -U postgres
- psql -c "create database eatsy owner eatsyuser;" -U postgres
- psql -c "ALTER ROLE eatsyuser Superuser;" -U postgres
- psql -c "ALTER USER eatsyuser CREATEDB;" -U postgres
- psql -c "ALTER DATABASE eatsy OWNER TO eatsyuser;" -U postgres
- psql -c "ALTER SCHEMA public OWNER TO CURRENT_USER;" -U postgres
- python manage.py makemigrations
language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd Eatsy
- cp travis_local_settings.py local_settings.py
- cd ..
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
- provider: heroku
  app: eatsy-develop
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: develop