# Generated by Django 3.1.7 on 2021-03-20 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=None)),
                ('descripcion', models.TextField(null=None)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('foto', models.TextField()),
                ('precioMedio', models.DecimalField(decimal_places=2, max_digits=6, null=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('dietas', models.CharField(choices=[('Vegano', 'Vegano'), ('Vegetariano', 'Vegetariano'), ('Gluten', 'Gluten'), ('Lactosa', 'Lactosa'), ('Marisco', 'Marisco'), ('Frutos secos', 'Frutos secos')], default='Vegetariano', max_length=12, verbose_name='Dieta')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Aceptado', 'Aceptado')], default='Pendiente', max_length=9, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=None)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.ubicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicaciones',
            field=models.ManyToManyField(through='product.UbicacionProducto', to='product.Ubicacion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.perfil'),
        ),
    ]
